### ISSUE TITLE
Cannot open presentation #7

### ISSUE THREAD

**Issue by Marcus-Brubaker-Prot** [microsoft/Fabric-Readiness#5]
When trying to open 07. Introduction to Microsoft Fabric for Power BI Users.pptx it requires signing in with an account. I tried using my company account and got the error: You are not signed in to Office with an account that has permission to open this presentation. I tried clicking "Add Account" and got into an endless loop of entering my office account and password. I tried "Request Permission" and got an error that my account could not be found in the microsoft.sharepoint.com directory. The other 6 presentations open without an issue.

<img width="434" alt="Screenshot 2023-09-07 113348" src="https://github.com/microsoft/Fabric-Readiness/assets/124208025/ff0fff41-fdb5-4da2-a17c-c4d9eced443e">

**Comment by vestergaardj** [comment]
I am seeing the same, when opening the file locally I get this
![image](https://github.com/microsoft/Fabric-Readiness/assets/108015731/6c7b2a2c-c0e3-430a-87d2-ce1bb732f1d7)

**Comment by toolboc** [comment]
It looks like there was a permission setting on the deck, thank you for raising this!  @vestergaardj / @Marcus-Brubaker-Prot , would you be able to confirm on your side that the deck opens without issue now then we can move to close, cheers!

**Comment by vestergaardj** [comment]
On my laptop: I it works both for download and view online
On tablet (iPad): It's not really a power point presentation, it more like a website without a stylesheet, looks really odd - but I get content

**Comment by Marcus-Brubaker-Prot** [comment]
> It looks like there was a confidentiality setting on the deck, thank you for raising this! @vestergaardj / @Marcus-Brubaker-Prot , would you be able to confirm on your side that the deck opens without issue now then we can move to close, cheers!

Yes presentation #7 working now. I can open it without issue.

**Comment by toolboc** [comment]
Thank you for verifying!  @vestergaardj , it looks like the preview online issue is related to the old version being cached (which should also no longer be the case.  Moving to close...
